import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class FormBeratBadan extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    int berat = 0;
    int tinggi = 0;
    int tinggi2 = 0;

    /**
     * Creates new form FormBeratBadan
     */
    public FormBeratBadan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Berat = new javax.swing.JTextField();
        Txt_Tinggi = new javax.swing.JTextField();
        Btn_Hitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kalkulator Berat Badan ");

        jLabel1.setText("Berat Badan (kg)");

        jLabel2.setText("Tinggi Badan (cm)");

        jLabel3.setText("Hasil:");

        Btn_Hitung.setText("Hitung");
        Btn_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1).addComponent(jLabel2))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Txt_Berat, javax.swing.GroupLayout.DEFAULT_SIZE, 100,
                                                        Short.MAX_VALUE)
                                                .addComponent(Txt_Tinggi)))))
                        .addGroup(layout.createSequentialGroup().addGap(143, 143, 143).addComponent(Btn_Hitung,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
                        .createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1).addComponent(Txt_Berat, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18).addComponent(jLabel2)).addComponent(Txt_Tinggi,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18).addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(Btn_Hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_HitungActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Btn_HitungActionPerformed
        // TODO add your handling code here:
        double berat = 0;

        try {
            berat = Integer.parseInt(Txt_Berat.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Bagian ini tidak boleh kosong!");
        }

        double tinggi = 0;

        try {
            tinggi = Double.parseDouble(Txt_Tinggi.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Bagian ini tidak boleh kosong!");
        }

        try {
            tinggi = tinggi / 100;
        } catch (ArithmeticException ae) {
            JOptionPane.showMessageDialog(null, "Tinggi tidak boleh 0!");
        }

        double tinggi2 = tinggi * tinggi;
        double hasil = berat / tinggi2;

        if (hasil < 18.5) {
            jLabel3.setText("Berat badan anda kurang");
        }

        else if ((hasil > 18.5) && (hasil < 23)) {
            jLabel3.setText("Berat badan anda ideal");
        }

        else {
            jLabel3.setText("Berat badan anda berlebih");
        }
    }// GEN-LAST:event_Btn_HitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBeratBadan.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBeratBadan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Hitung;
    private javax.swing.JTextField Txt_Berat;
    private javax.swing.JTextField Txt_Tinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
